/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionAnalyzerRouteImport } from './routes/transaction-analyzer'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as GeographicRouteImport } from './routes/geographic'
import { Route as CustomerFeedbackRouteImport } from './routes/customer-feedback'
import { Route as CustomerCareRouteImport } from './routes/customer-care'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApplicationHealthRouteImport } from './routes/application-health'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as AdminCramRouteImport } from './routes/admin.cram'
import { Route as AdminCramIndexRouteImport } from './routes/admin.cram.index'
import { Route as AdminCramWorkflowsRouteImport } from './routes/admin.cram.workflows'
import { Route as AdminCramSimulatorRouteImport } from './routes/admin.cram.simulator'
import { Route as AdminCramRolesRouteImport } from './routes/admin.cram.roles'
import { Route as AdminCramRiskModelRouteImport } from './routes/admin.cram.risk-model'
import { Route as AdminCramRatingsRouteImport } from './routes/admin.cram.ratings'
import { Route as AdminCramProductRouteImport } from './routes/admin.cram.product'
import { Route as AdminCramOverrideRulesRouteImport } from './routes/admin.cram.override-rules'
import { Route as AdminCramGeographyRouteImport } from './routes/admin.cram.geography'
import { Route as AdminCramDecisionMatrixRouteImport } from './routes/admin.cram.decision-matrix'
import { Route as AdminCramAuditLogsRouteImport } from './routes/admin.cram.audit-logs'
import { Route as AdminCramAssessmentsRouteImport } from './routes/admin.cram.assessments'

const TransactionAnalyzerRoute = TransactionAnalyzerRouteImport.update({
  id: '/transaction-analyzer',
  path: '/transaction-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const GeographicRoute = GeographicRouteImport.update({
  id: '/geographic',
  path: '/geographic',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerFeedbackRoute = CustomerFeedbackRouteImport.update({
  id: '/customer-feedback',
  path: '/customer-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCareRoute = CustomerCareRouteImport.update({
  id: '/customer-care',
  path: '/customer-care',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationHealthRoute = ApplicationHealthRouteImport.update({
  id: '/application-health',
  path: '/application-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => IssuesRoute,
} as any)
const AdminCramRoute = AdminCramRouteImport.update({
  id: '/cram',
  path: '/cram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCramIndexRoute = AdminCramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramWorkflowsRoute = AdminCramWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramSimulatorRoute = AdminCramSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramRolesRoute = AdminCramRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramRiskModelRoute = AdminCramRiskModelRouteImport.update({
  id: '/risk-model',
  path: '/risk-model',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramRatingsRoute = AdminCramRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramProductRoute = AdminCramProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramOverrideRulesRoute = AdminCramOverrideRulesRouteImport.update({
  id: '/override-rules',
  path: '/override-rules',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramGeographyRoute = AdminCramGeographyRouteImport.update({
  id: '/geography',
  path: '/geography',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramDecisionMatrixRoute = AdminCramDecisionMatrixRouteImport.update({
  id: '/decision-matrix',
  path: '/decision-matrix',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramAuditLogsRoute = AdminCramAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminCramRoute,
} as any)
const AdminCramAssessmentsRoute = AdminCramAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AdminCramRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/application-health': typeof ApplicationHealthRoute
  '/assistant': typeof AssistantRoute
  '/customer-care': typeof CustomerCareRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/geographic': typeof GeographicRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/ratings': typeof RatingsRoute
  '/recommendations': typeof RecommendationsRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/social': typeof SocialRoute
  '/surveys': typeof SurveysRoute
  '/transaction-analyzer': typeof TransactionAnalyzerRoute
  '/admin/cram': typeof AdminCramRouteWithChildren
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cram/assessments': typeof AdminCramAssessmentsRoute
  '/admin/cram/audit-logs': typeof AdminCramAuditLogsRoute
  '/admin/cram/decision-matrix': typeof AdminCramDecisionMatrixRoute
  '/admin/cram/geography': typeof AdminCramGeographyRoute
  '/admin/cram/override-rules': typeof AdminCramOverrideRulesRoute
  '/admin/cram/product': typeof AdminCramProductRoute
  '/admin/cram/ratings': typeof AdminCramRatingsRoute
  '/admin/cram/risk-model': typeof AdminCramRiskModelRoute
  '/admin/cram/roles': typeof AdminCramRolesRoute
  '/admin/cram/simulator': typeof AdminCramSimulatorRoute
  '/admin/cram/workflows': typeof AdminCramWorkflowsRoute
  '/admin/cram/': typeof AdminCramIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/application-health': typeof ApplicationHealthRoute
  '/assistant': typeof AssistantRoute
  '/customer-care': typeof CustomerCareRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/geographic': typeof GeographicRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/ratings': typeof RatingsRoute
  '/recommendations': typeof RecommendationsRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/social': typeof SocialRoute
  '/surveys': typeof SurveysRoute
  '/transaction-analyzer': typeof TransactionAnalyzerRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cram/assessments': typeof AdminCramAssessmentsRoute
  '/admin/cram/audit-logs': typeof AdminCramAuditLogsRoute
  '/admin/cram/decision-matrix': typeof AdminCramDecisionMatrixRoute
  '/admin/cram/geography': typeof AdminCramGeographyRoute
  '/admin/cram/override-rules': typeof AdminCramOverrideRulesRoute
  '/admin/cram/product': typeof AdminCramProductRoute
  '/admin/cram/ratings': typeof AdminCramRatingsRoute
  '/admin/cram/risk-model': typeof AdminCramRiskModelRoute
  '/admin/cram/roles': typeof AdminCramRolesRoute
  '/admin/cram/simulator': typeof AdminCramSimulatorRoute
  '/admin/cram/workflows': typeof AdminCramWorkflowsRoute
  '/admin/cram': typeof AdminCramIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/application-health': typeof ApplicationHealthRoute
  '/assistant': typeof AssistantRoute
  '/customer-care': typeof CustomerCareRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/geographic': typeof GeographicRoute
  '/issues': typeof IssuesRouteWithChildren
  '/login': typeof LoginRoute
  '/ratings': typeof RatingsRoute
  '/recommendations': typeof RecommendationsRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/social': typeof SocialRoute
  '/surveys': typeof SurveysRoute
  '/transaction-analyzer': typeof TransactionAnalyzerRoute
  '/admin/cram': typeof AdminCramRouteWithChildren
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cram/assessments': typeof AdminCramAssessmentsRoute
  '/admin/cram/audit-logs': typeof AdminCramAuditLogsRoute
  '/admin/cram/decision-matrix': typeof AdminCramDecisionMatrixRoute
  '/admin/cram/geography': typeof AdminCramGeographyRoute
  '/admin/cram/override-rules': typeof AdminCramOverrideRulesRoute
  '/admin/cram/product': typeof AdminCramProductRoute
  '/admin/cram/ratings': typeof AdminCramRatingsRoute
  '/admin/cram/risk-model': typeof AdminCramRiskModelRoute
  '/admin/cram/roles': typeof AdminCramRolesRoute
  '/admin/cram/simulator': typeof AdminCramSimulatorRoute
  '/admin/cram/workflows': typeof AdminCramWorkflowsRoute
  '/admin/cram/': typeof AdminCramIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/application-health'
    | '/assistant'
    | '/customer-care'
    | '/customer-feedback'
    | '/geographic'
    | '/issues'
    | '/login'
    | '/ratings'
    | '/recommendations'
    | '/releases'
    | '/reports'
    | '/sentiment'
    | '/social'
    | '/surveys'
    | '/transaction-analyzer'
    | '/admin/cram'
    | '/issues/$issueId'
    | '/admin/'
    | '/admin/cram/assessments'
    | '/admin/cram/audit-logs'
    | '/admin/cram/decision-matrix'
    | '/admin/cram/geography'
    | '/admin/cram/override-rules'
    | '/admin/cram/product'
    | '/admin/cram/ratings'
    | '/admin/cram/risk-model'
    | '/admin/cram/roles'
    | '/admin/cram/simulator'
    | '/admin/cram/workflows'
    | '/admin/cram/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-health'
    | '/assistant'
    | '/customer-care'
    | '/customer-feedback'
    | '/geographic'
    | '/issues'
    | '/login'
    | '/ratings'
    | '/recommendations'
    | '/releases'
    | '/reports'
    | '/sentiment'
    | '/social'
    | '/surveys'
    | '/transaction-analyzer'
    | '/issues/$issueId'
    | '/admin'
    | '/admin/cram/assessments'
    | '/admin/cram/audit-logs'
    | '/admin/cram/decision-matrix'
    | '/admin/cram/geography'
    | '/admin/cram/override-rules'
    | '/admin/cram/product'
    | '/admin/cram/ratings'
    | '/admin/cram/risk-model'
    | '/admin/cram/roles'
    | '/admin/cram/simulator'
    | '/admin/cram/workflows'
    | '/admin/cram'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/application-health'
    | '/assistant'
    | '/customer-care'
    | '/customer-feedback'
    | '/geographic'
    | '/issues'
    | '/login'
    | '/ratings'
    | '/recommendations'
    | '/releases'
    | '/reports'
    | '/sentiment'
    | '/social'
    | '/surveys'
    | '/transaction-analyzer'
    | '/admin/cram'
    | '/issues/$issueId'
    | '/admin/'
    | '/admin/cram/assessments'
    | '/admin/cram/audit-logs'
    | '/admin/cram/decision-matrix'
    | '/admin/cram/geography'
    | '/admin/cram/override-rules'
    | '/admin/cram/product'
    | '/admin/cram/ratings'
    | '/admin/cram/risk-model'
    | '/admin/cram/roles'
    | '/admin/cram/simulator'
    | '/admin/cram/workflows'
    | '/admin/cram/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplicationHealthRoute: typeof ApplicationHealthRoute
  AssistantRoute: typeof AssistantRoute
  CustomerCareRoute: typeof CustomerCareRoute
  CustomerFeedbackRoute: typeof CustomerFeedbackRoute
  GeographicRoute: typeof GeographicRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  LoginRoute: typeof LoginRoute
  RatingsRoute: typeof RatingsRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ReleasesRoute: typeof ReleasesRoute
  ReportsRoute: typeof ReportsRoute
  SentimentRoute: typeof SentimentRoute
  SocialRoute: typeof SocialRoute
  SurveysRoute: typeof SurveysRoute
  TransactionAnalyzerRoute: typeof TransactionAnalyzerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaction-analyzer': {
      id: '/transaction-analyzer'
      path: '/transaction-analyzer'
      fullPath: '/transaction-analyzer'
      preLoaderRoute: typeof TransactionAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geographic': {
      id: '/geographic'
      path: '/geographic'
      fullPath: '/geographic'
      preLoaderRoute: typeof GeographicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-feedback': {
      id: '/customer-feedback'
      path: '/customer-feedback'
      fullPath: '/customer-feedback'
      preLoaderRoute: typeof CustomerFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-care': {
      id: '/customer-care'
      path: '/customer-care'
      fullPath: '/customer-care'
      preLoaderRoute: typeof CustomerCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-health': {
      id: '/application-health'
      path: '/application-health'
      fullPath: '/application-health'
      preLoaderRoute: typeof ApplicationHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/admin/cram': {
      id: '/admin/cram'
      path: '/cram'
      fullPath: '/admin/cram'
      preLoaderRoute: typeof AdminCramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cram/': {
      id: '/admin/cram/'
      path: '/'
      fullPath: '/admin/cram/'
      preLoaderRoute: typeof AdminCramIndexRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/workflows': {
      id: '/admin/cram/workflows'
      path: '/workflows'
      fullPath: '/admin/cram/workflows'
      preLoaderRoute: typeof AdminCramWorkflowsRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/simulator': {
      id: '/admin/cram/simulator'
      path: '/simulator'
      fullPath: '/admin/cram/simulator'
      preLoaderRoute: typeof AdminCramSimulatorRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/roles': {
      id: '/admin/cram/roles'
      path: '/roles'
      fullPath: '/admin/cram/roles'
      preLoaderRoute: typeof AdminCramRolesRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/risk-model': {
      id: '/admin/cram/risk-model'
      path: '/risk-model'
      fullPath: '/admin/cram/risk-model'
      preLoaderRoute: typeof AdminCramRiskModelRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/ratings': {
      id: '/admin/cram/ratings'
      path: '/ratings'
      fullPath: '/admin/cram/ratings'
      preLoaderRoute: typeof AdminCramRatingsRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/product': {
      id: '/admin/cram/product'
      path: '/product'
      fullPath: '/admin/cram/product'
      preLoaderRoute: typeof AdminCramProductRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/override-rules': {
      id: '/admin/cram/override-rules'
      path: '/override-rules'
      fullPath: '/admin/cram/override-rules'
      preLoaderRoute: typeof AdminCramOverrideRulesRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/geography': {
      id: '/admin/cram/geography'
      path: '/geography'
      fullPath: '/admin/cram/geography'
      preLoaderRoute: typeof AdminCramGeographyRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/decision-matrix': {
      id: '/admin/cram/decision-matrix'
      path: '/decision-matrix'
      fullPath: '/admin/cram/decision-matrix'
      preLoaderRoute: typeof AdminCramDecisionMatrixRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/audit-logs': {
      id: '/admin/cram/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/cram/audit-logs'
      preLoaderRoute: typeof AdminCramAuditLogsRouteImport
      parentRoute: typeof AdminCramRoute
    }
    '/admin/cram/assessments': {
      id: '/admin/cram/assessments'
      path: '/assessments'
      fullPath: '/admin/cram/assessments'
      preLoaderRoute: typeof AdminCramAssessmentsRouteImport
      parentRoute: typeof AdminCramRoute
    }
  }
}

interface AdminCramRouteChildren {
  AdminCramAssessmentsRoute: typeof AdminCramAssessmentsRoute
  AdminCramAuditLogsRoute: typeof AdminCramAuditLogsRoute
  AdminCramDecisionMatrixRoute: typeof AdminCramDecisionMatrixRoute
  AdminCramGeographyRoute: typeof AdminCramGeographyRoute
  AdminCramOverrideRulesRoute: typeof AdminCramOverrideRulesRoute
  AdminCramProductRoute: typeof AdminCramProductRoute
  AdminCramRatingsRoute: typeof AdminCramRatingsRoute
  AdminCramRiskModelRoute: typeof AdminCramRiskModelRoute
  AdminCramRolesRoute: typeof AdminCramRolesRoute
  AdminCramSimulatorRoute: typeof AdminCramSimulatorRoute
  AdminCramWorkflowsRoute: typeof AdminCramWorkflowsRoute
  AdminCramIndexRoute: typeof AdminCramIndexRoute
}

const AdminCramRouteChildren: AdminCramRouteChildren = {
  AdminCramAssessmentsRoute: AdminCramAssessmentsRoute,
  AdminCramAuditLogsRoute: AdminCramAuditLogsRoute,
  AdminCramDecisionMatrixRoute: AdminCramDecisionMatrixRoute,
  AdminCramGeographyRoute: AdminCramGeographyRoute,
  AdminCramOverrideRulesRoute: AdminCramOverrideRulesRoute,
  AdminCramProductRoute: AdminCramProductRoute,
  AdminCramRatingsRoute: AdminCramRatingsRoute,
  AdminCramRiskModelRoute: AdminCramRiskModelRoute,
  AdminCramRolesRoute: AdminCramRolesRoute,
  AdminCramSimulatorRoute: AdminCramSimulatorRoute,
  AdminCramWorkflowsRoute: AdminCramWorkflowsRoute,
  AdminCramIndexRoute: AdminCramIndexRoute,
}

const AdminCramRouteWithChildren = AdminCramRoute._addFileChildren(
  AdminCramRouteChildren,
)

interface AdminRouteChildren {
  AdminCramRoute: typeof AdminCramRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCramRoute: AdminCramRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface IssuesRouteChildren {
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIssueIdRoute: IssuesIssueIdRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplicationHealthRoute: ApplicationHealthRoute,
  AssistantRoute: AssistantRoute,
  CustomerCareRoute: CustomerCareRoute,
  CustomerFeedbackRoute: CustomerFeedbackRoute,
  GeographicRoute: GeographicRoute,
  IssuesRoute: IssuesRouteWithChildren,
  LoginRoute: LoginRoute,
  RatingsRoute: RatingsRoute,
  RecommendationsRoute: RecommendationsRoute,
  ReleasesRoute: ReleasesRoute,
  ReportsRoute: ReportsRoute,
  SentimentRoute: SentimentRoute,
  SocialRoute: SocialRoute,
  SurveysRoute: SurveysRoute,
  TransactionAnalyzerRoute: TransactionAnalyzerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
