/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as GeographicRouteImport } from './routes/geographic'
import { Route as CustomerFeedbackRouteImport } from './routes/customer-feedback'
import { Route as CustomerCareRouteImport } from './routes/customer-care'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApplicationHealthRouteImport } from './routes/application-health'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'

const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const GeographicRoute = GeographicRouteImport.update({
  id: '/geographic',
  path: '/geographic',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerFeedbackRoute = CustomerFeedbackRouteImport.update({
  id: '/customer-feedback',
  path: '/customer-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCareRoute = CustomerCareRouteImport.update({
  id: '/customer-care',
  path: '/customer-care',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationHealthRoute = ApplicationHealthRouteImport.update({
  id: '/application-health',
  path: '/application-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/$issueId',
  path: '/$issueId',
  getParentRoute: () => IssuesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/application-health': typeof ApplicationHealthRoute
  '/assistant': typeof AssistantRoute
  '/customer-care': typeof CustomerCareRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/geographic': typeof GeographicRoute
  '/issues': typeof IssuesRouteWithChildren
  '/ratings': typeof RatingsRoute
  '/recommendations': typeof RecommendationsRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/social': typeof SocialRoute
  '/surveys': typeof SurveysRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/application-health': typeof ApplicationHealthRoute
  '/assistant': typeof AssistantRoute
  '/customer-care': typeof CustomerCareRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/geographic': typeof GeographicRoute
  '/issues': typeof IssuesRouteWithChildren
  '/ratings': typeof RatingsRoute
  '/recommendations': typeof RecommendationsRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/social': typeof SocialRoute
  '/surveys': typeof SurveysRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/application-health': typeof ApplicationHealthRoute
  '/assistant': typeof AssistantRoute
  '/customer-care': typeof CustomerCareRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/geographic': typeof GeographicRoute
  '/issues': typeof IssuesRouteWithChildren
  '/ratings': typeof RatingsRoute
  '/recommendations': typeof RecommendationsRoute
  '/releases': typeof ReleasesRoute
  '/reports': typeof ReportsRoute
  '/sentiment': typeof SentimentRoute
  '/social': typeof SocialRoute
  '/surveys': typeof SurveysRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/application-health'
    | '/assistant'
    | '/customer-care'
    | '/customer-feedback'
    | '/geographic'
    | '/issues'
    | '/ratings'
    | '/recommendations'
    | '/releases'
    | '/reports'
    | '/sentiment'
    | '/social'
    | '/surveys'
    | '/issues/$issueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/application-health'
    | '/assistant'
    | '/customer-care'
    | '/customer-feedback'
    | '/geographic'
    | '/issues'
    | '/ratings'
    | '/recommendations'
    | '/releases'
    | '/reports'
    | '/sentiment'
    | '/social'
    | '/surveys'
    | '/issues/$issueId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/application-health'
    | '/assistant'
    | '/customer-care'
    | '/customer-feedback'
    | '/geographic'
    | '/issues'
    | '/ratings'
    | '/recommendations'
    | '/releases'
    | '/reports'
    | '/sentiment'
    | '/social'
    | '/surveys'
    | '/issues/$issueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplicationHealthRoute: typeof ApplicationHealthRoute
  AssistantRoute: typeof AssistantRoute
  CustomerCareRoute: typeof CustomerCareRoute
  CustomerFeedbackRoute: typeof CustomerFeedbackRoute
  GeographicRoute: typeof GeographicRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  RatingsRoute: typeof RatingsRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ReleasesRoute: typeof ReleasesRoute
  ReportsRoute: typeof ReportsRoute
  SentimentRoute: typeof SentimentRoute
  SocialRoute: typeof SocialRoute
  SurveysRoute: typeof SurveysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geographic': {
      id: '/geographic'
      path: '/geographic'
      fullPath: '/geographic'
      preLoaderRoute: typeof GeographicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-feedback': {
      id: '/customer-feedback'
      path: '/customer-feedback'
      fullPath: '/customer-feedback'
      preLoaderRoute: typeof CustomerFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-care': {
      id: '/customer-care'
      path: '/customer-care'
      fullPath: '/customer-care'
      preLoaderRoute: typeof CustomerCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-health': {
      id: '/application-health'
      path: '/application-health'
      fullPath: '/application-health'
      preLoaderRoute: typeof ApplicationHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof IssuesRoute
    }
  }
}

interface IssuesRouteChildren {
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIssueIdRoute: IssuesIssueIdRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplicationHealthRoute: ApplicationHealthRoute,
  AssistantRoute: AssistantRoute,
  CustomerCareRoute: CustomerCareRoute,
  CustomerFeedbackRoute: CustomerFeedbackRoute,
  GeographicRoute: GeographicRoute,
  IssuesRoute: IssuesRouteWithChildren,
  RatingsRoute: RatingsRoute,
  RecommendationsRoute: RecommendationsRoute,
  ReleasesRoute: ReleasesRoute,
  ReportsRoute: ReportsRoute,
  SentimentRoute: SentimentRoute,
  SocialRoute: SocialRoute,
  SurveysRoute: SurveysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
